version: "3"
services:
    mongo:
        image: "mongo:latest"
        container_name: media.mongo
        ports:
            - 27017:27017
        expose:
            - 27017
 
    mongo_seed:
        image: mongo:latest
        links:
            - mongo
        volumes:
            - ./mongo_seed:/mongo_seed
        command:
            /mongo_seed/import.sh   

    platform:
       container_name: media.platform
       build: .
       env_file: .env
       depends_on: 
           - mongo
       ports:
           - 8000:8000
       